-- Soft-delete a challenge and the OPEN tasks it generated.
--
-- SOFT, not hard: every other delete in this app sets deleted_at, and every
-- query already filters on it, so the record disappears from the product without
-- destroying the challenge's status history, journal entries or stakeholder
-- rows. On a government platform a record that vanishes without trace is a
-- compliance problem, and a misclick should not be unrecoverable.
--
-- OPEN tasks only. Closed tasks are a record of work somebody actually did, and
-- they feed that person's performance score. Deleting them would retroactively
-- lower a colleague's Volume and Timeliness for work they genuinely completed,
-- with no notification and no way for them to discover why.
--
-- SECURITY DEFINER with an explicit super check: challenges_update already
-- permits current_user_is_manager(), so relying on RLS would let any manager
-- delete. Enforcing it in the UI alone is weaker still — anyone holding the anon
-- key could issue the update directly.

CREATE OR REPLACE FUNCTION public.soft_delete_challenge(p_challenge_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_now           timestamptz := now();
  v_tasks_deleted int;
  v_found         int;
BEGIN
  IF NOT current_user_is_super() THEN
    RAISE EXCEPTION 'not_authorised';
  END IF;

  -- open tasks generated by this challenge
  UPDATE public.tasks
     SET deleted_at = v_now,
         updated_at = v_now
   WHERE source_challenge_id = p_challenge_id
     AND deleted_at IS NULL
     AND status::text NOT IN ('done', 'cancelled');
  GET DIAGNOSTICS v_tasks_deleted = ROW_COUNT;

  -- the challenge itself
  UPDATE public.challenges
     SET deleted_at = v_now,
         updated_at = v_now
   WHERE id = p_challenge_id
     AND deleted_at IS NULL;
  GET DIAGNOSTICS v_found = ROW_COUNT;

  IF v_found = 0 THEN
    RAISE EXCEPTION 'challenge_not_found_or_already_deleted';
  END IF;

  RETURN jsonb_build_object('tasksDeleted', v_tasks_deleted);
END;
$$;

COMMENT ON FUNCTION public.soft_delete_challenge IS
  'Super-admin only. Soft-deletes a challenge and its OPEN tasks; closed tasks are kept because they record work already done and feed performance scores.';
